export const categoryMeta = {
  application_received: { label: "申请已收到", tone: "slate" },
  rejected: { label: "拒绝", tone: "red" },
  assessment_invite: { label: "测评邀请", tone: "amber" },
  written_test_invite: { label: "笔试邀请", tone: "violet" },
  interview_invite: { label: "面试邀请", tone: "blue" },
  offer: { label: "Offer", tone: "green" },
  other: { label: "广告/无关", tone: "muted" },
  unclassified: { label: "未分类", tone: "muted" },
};

export const companies = [
  { id: "bytedance", name: "字节跳动", status: "面试中", positionCount: 6, tone: "indigo" },
  { id: "meituan", name: "美团", status: "笔试中", positionCount: 6, tone: "amber" },
  { id: "tencent", name: "腾讯", status: "笔试中", positionCount: 6, tone: "blue" },
  { id: "alibaba", name: "阿里巴巴", status: "面试中", positionCount: 6, tone: "orange" },
  { id: "huawei", name: "华为", status: "Offer", positionCount: 5, tone: "green" },
  { id: "jingdong", name: "京东", status: "测评中", positionCount: 5, tone: "red" },
  { id: "baidu", name: "百度", status: "申请已收到", positionCount: 4, tone: "slate" },
  { id: "unknown", name: "某公司", status: "已拒绝", positionCount: 1, tone: "muted" },
  { id: "other", name: "其他", status: "广告/无关", positionCount: 0, tone: "muted", isOther: true },
];

export const emails = [
  {
    id: "mail-01",
    companyId: "bytedance",
    company: "字节跳动",
    position: "后端开发",
    category: "interview_invite",
    subject: "诚邀您参加字节跳动后端开发岗位面试",
    snippet: "您好，我们诚邀您参加字节跳动后端开发岗位面试",
    body: "您好，我们诚邀您参加字节跳动后端开发岗位面试。面试预计安排在 9 月 18 日，请点击邮件中的链接确认是否参加，并在确认后留意后续会议通知。",
    receivedAt: "2026-09-11T09:30:00+08:00",
    eventDate: "2026-09-18",
    eventType: "interview",
    canComplete: true,
    unread: true,
  },
  {
    id: "mail-02",
    companyId: "meituan",
    company: "美团",
    position: "数据开发",
    category: "assessment_invite",
    subject: "美团数据开发岗位在线测评邀请",
    snippet: "您好，请于 09-11 前完成在线测评",
    body: "您好，感谢您投递美团数据开发岗位。请于 9 月 11 日前完成在线测评，逾期将视为放弃本次机会。",
    receivedAt: "2026-09-11T08:45:00+08:00",
    deadline: "2026-09-11",
    canComplete: true,
    unread: true,
  },
  {
    id: "mail-03",
    companyId: "tencent",
    company: "腾讯",
    position: "客户端开发",
    category: "written_test_invite",
    subject: "腾讯客户端开发岗位笔试通知",
    snippet: "恭喜您通过简历筛选，请于 09-12 前完成笔试",
    body: "恭喜您通过腾讯客户端开发岗位简历筛选。请在 9 月 12 日前完成本次在线笔试，具体入口和考试说明见邮件正文。",
    receivedAt: "2026-09-11T08:10:00+08:00",
    deadline: "2026-09-12",
    canComplete: true,
    unread: true,
  },
  {
    id: "mail-04",
    companyId: "huawei",
    company: "华为",
    position: "算法工程师",
    category: "offer",
    subject: "华为算法工程师录用通知",
    snippet: "很高兴向您发出华为算法工程师岗位录用通知",
    body: "感谢您参加华为算法工程师岗位面试，我们很高兴向您发出录用通知。请按照邮件附件中的说明完成后续确认。",
    receivedAt: "2026-09-10T18:20:00+08:00",
    canComplete: false,
    unread: false,
  },
  {
    id: "mail-05",
    companyId: "alibaba",
    company: "阿里巴巴",
    position: "AI 产品经理",
    category: "assessment_invite",
    subject: "阿里巴巴 AI 产品经理测评邀请",
    snippet: "请于 09-18 前完成岗位测评",
    body: "您好，您的简历已进入阿里巴巴 AI 产品经理岗位评估阶段。请在 9 月 18 日前完成在线测评。",
    receivedAt: "2026-09-10T14:00:00+08:00",
    deadline: "2026-09-18",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-06",
    companyId: "jingdong",
    company: "京东",
    position: "数据分析",
    category: "written_test_invite",
    subject: "京东数据分析岗位笔试安排",
    snippet: "请于 09-12 前完成京东数据分析笔试",
    body: "您好，您已通过京东数据分析岗位简历筛选。请于 9 月 12 日前完成在线笔试，笔试链接和账号信息请妥善保管。",
    receivedAt: "2026-09-10T10:00:00+08:00",
    deadline: "2026-09-12",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-07",
    companyId: "tencent",
    company: "腾讯",
    position: "客户端开发",
    category: "assessment_invite",
    subject: "腾讯客户端开发岗位测评通知",
    snippet: "请在 09-18 前完成本次岗位测评",
    body: "您好，腾讯客户端开发岗位需要您完成一次在线测评，请于 9 月 18 日前完成。",
    receivedAt: "2026-09-09T09:00:00+08:00",
    deadline: "2026-09-18",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-08",
    companyId: "unknown",
    company: "某公司",
    position: "产品经理",
    category: "rejected",
    subject: "关于您的产品经理岗位申请",
    snippet: "感谢您的关注，本次岗位暂不匹配",
    body: "感谢您的关注。经过综合评估，您本次产品经理岗位的申请暂不匹配，祝您后续求职顺利。",
    receivedAt: "2026-09-09T15:00:00+08:00",
    canComplete: false,
    unread: false,
  },
  {
    id: "mail-09",
    companyId: "other",
    company: "其他",
    position: null,
    category: "other",
    isOther: true,
    subject: "限时开放：秋招训练营报名中",
    snippet: "加入秋招训练营，领取简历模板和面试课程",
    body: "限时开放，加入秋招训练营，领取简历模板和面试课程。该邮件为系统识别到的广告或无关邮件，不会进入秋招流程。",
    receivedAt: "2026-09-08T11:20:00+08:00",
    canComplete: false,
    unread: false,
  },
  {
    id: "mail-10",
    companyId: "alibaba",
    company: "阿里巴巴",
    position: "AI 产品经理",
    category: "interview_invite",
    subject: "阿里巴巴 AI 产品经理面试邀约",
    snippet: "诚邀您参加阿里巴巴 AI 产品经理岗位面试",
    body: "您好，经过评估，我们诚邀您参加阿里巴巴 AI 产品经理岗位面试。面试时间预计为 9 月 17 日，请确认是否参加。",
    receivedAt: "2026-09-08T17:30:00+08:00",
    eventDate: "2026-09-17",
    eventType: "interview",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-11",
    companyId: "meituan",
    company: "美团",
    position: "数据开发",
    category: "written_test_invite",
    subject: "美团数据开发岗位笔试确认",
    snippet: "请于 09-18 前完成美团在线笔试",
    body: "您好，您已进入美团数据开发岗位笔试环节。请在 9 月 18 日前完成在线笔试，并在完成后留意后续通知。",
    receivedAt: "2026-09-07T10:30:00+08:00",
    deadline: "2026-09-18",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-12",
    companyId: "huawei",
    company: "华为",
    position: "算法工程师",
    category: "interview_invite",
    subject: "华为算法工程师面试安排",
    snippet: "您的算法工程师岗位面试预计在 09-13 进行",
    body: "您好，您的华为算法工程师岗位面试预计在 9 月 13 日进行。请提前准备并按时进入线上会议。",
    receivedAt: "2026-09-06T15:00:00+08:00",
    eventDate: "2026-09-13",
    eventType: "interview",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-13",
    companyId: "baidu",
    company: "百度",
    position: "机器学习",
    category: "application_received",
    subject: "百度机器学习岗位申请已收到",
    snippet: "感谢您投递百度机器学习岗位",
    body: "感谢您投递百度机器学习岗位，我们已收到您的申请，后续进展会通过邮件通知您。",
    receivedAt: "2026-09-05T12:00:00+08:00",
    canComplete: false,
    unread: false,
  },
  {
    id: "mail-14",
    companyId: "meituan",
    company: "美团",
    position: "数据开发",
    category: "interview_invite",
    subject: "美团数据开发岗位面试邀约",
    snippet: "诚邀您参加美团数据开发岗位线上面试",
    body: "您好，诚邀您参加美团数据开发岗位线上面试。面试时间预计为 9 月 14 日，请确认参加。",
    receivedAt: "2026-09-05T11:00:00+08:00",
    eventDate: "2026-09-14",
    eventType: "interview",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-15",
    companyId: "jingdong",
    company: "京东",
    position: "数据分析",
    category: "assessment_invite",
    subject: "京东数据分析岗位测评邀请",
    snippet: "请于 09-09 前完成京东在线测评",
    body: "您好，请于 9 月 9 日前完成京东数据分析岗位在线测评。该通知已超过截止日期，请尽快确认是否已经完成。",
    receivedAt: "2026-09-04T09:30:00+08:00",
    deadline: "2026-09-09",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-16",
    companyId: "bytedance",
    company: "字节跳动",
    position: "后端开发",
    category: "assessment_invite",
    subject: "字节跳动后端开发在线测评",
    snippet: "请在 09-18 前完成字节跳动在线测评",
    body: "您好，您在字节跳动后端开发岗位的申请已进入测评阶段，请在 9 月 18 日前完成在线测评。",
    receivedAt: "2026-09-03T16:00:00+08:00",
    deadline: "2026-09-18",
    canComplete: true,
    unread: false,
  },
  {
    id: "mail-17",
    companyId: "bytedance",
    company: "字节跳动",
    position: "后端开发",
    category: "application_received",
    subject: "字节跳动后端开发申请已收到",
    snippet: "感谢您投递字节跳动后端开发岗位",
    body: "感谢您投递字节跳动后端开发岗位，我们已收到您的申请，后续进展会通过邮件通知您。",
    receivedAt: "2026-09-01T10:00:00+08:00",
    canComplete: false,
    unread: false,
  },
  {
    id: "mail-18",
    companyId: "other",
    company: "其他",
    position: null,
    category: "other",
    isOther: true,
    subject: "校招简历优化服务限时优惠",
    snippet: "专业导师一对一修改简历，限时优惠",
    body: "校招简历优化服务限时优惠，专业导师一对一修改简历。该邮件为系统识别到的广告或无关邮件。",
    receivedAt: "2026-09-02T12:00:00+08:00",
    canComplete: false,
    unread: false,
  },
];
